services:
    Creonit\SmsBundle\Admin\SmsModule:
        tags:
            - { name: creonit_admin.module }

    Creonit\SmsBundle\SmsMessenger:
        class: Creonit\SmsBundle\SmsMessenger
        autowire: true
        autoconfigure: true

    creonit.messenger.sms_handler:
        alias: Creonit\SmsBundle\SmsMessenger
        public: true

    Creonit\SmsBundle\Transport\:
        resource: '../../Transport/*Transport.php'
        autowire: true
        autoconfigure: true

    Creonit\SmsBundle\Service\SmsLogService:
        autowire: true
        autoconfigure: true

    creonit.sms.sms_traffic_transport:
        alias: Creonit\SmsBundle\Transport\SmsTrafficTransport

    creonit.sms.logger_transport:
        alias: Creonit\SmsBundle\Transport\LoggerTransport

